### ISSUE TITLE
Use of many code chunks

### ISSUE THREAD

**Issue by mgdondon** [Hemken/SASmarkdown#12]
Hello,

The export to HTML, PDF and Word is OK if I run many SAS proc in the same code chunk :

\```{r, engine='sas', collectcode=TRUE, error=TRUE}
```
proc print data=sashelp.class (obs=3);
run;

proc means data=sashelp.class;
  var Age Height Weight;
run;

                  Obs.     Name      Sex    Age    Height    Weight

                    1     Alfred      M      14     69.0      112.5
                    2     Alice       F      13     56.5       84.0
                    3     Barbara     F      13     65.3       98.0
 
                                                                                     
 
                                   Procédure MEANS

   Variable     N         Moyenne      Ecart-type         Minimum         Maximum
   ------------------------------------------------------------------------------
   Age         19      13.3157895       1.4926722      11.0000000      16.0000000
   Height      19      62.3368421       5.1270752      51.3000000      72.0000000
   Weight      19     100.0263158      22.7739335      50.5000000     150.0000000
   ------------------------------------------------------------------------------
```

but not if I use many code chunks :

\```{r, engine='sas', collectcode=TRUE, error=TRUE}
```
proc print data=sashelp.class (obs=3);
run;

                  Obs.     Name      Sex    Age    Height    Weight

                    1     Alfred      M      14     69.0      112.5
                    2     Alice       F      13     56.5       84.0
                    3     Barbara     F      13     65.3       98.0
```

\```{r, engine='sas', collectcode=TRUE, error=TRUE}
```
proc means data=sashelp.class;
  var Age Height Weight;
run;

                                                                     Le Système SAS 1
                                                      20:00 Wednesday, March 11, 2020

                  Obs.     Name      Sex    Age    Height    Weight

                    1     Alfred      M      14     69.0      112.5
                    2     Alice       F      13     56.5       84.0
                    3     Barbara     F      13     65.3       98.0
 
                                                                                     
 
                                   Procédure MEANS

   Variable     N         Moyenne      Ecart-type         Minimum         Maximum
   ------------------------------------------------------------------------------
   Age         19      13.3157895       1.4926722      11.0000000      16.0000000
   Height      19      62.3368421       5.1270752      51.3000000      72.0000000
   Weight      19     100.0263158      22.7739335      50.5000000     150.0000000
   ------------------------------------------------------------------------------
```

Session info :
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] SASmarkdown_0.5.2

loaded via a namespace (and not attached):
 [1] compiler_3.6.3  htmltools_0.4.0 tools_3.6.3     yaml_2.2.1      Rcpp_1.0.3      rmarkdown_2.1  
 [7] knitr_1.28      digest_0.6.25   xfun_0.12       rlang_0.4.5     evaluate_0.14  
```

Many thanks,

**Comment by Hemken** [comment]
Could you send me your sample markdown file?

**Comment by mgdondon** [comment]
[sasmarkdown.Rmd.txt](https://github.com/Hemken/SASmarkdown/files/4320542/sasmarkdown.Rmd.txt)

Many thanks,

**Comment by Hemken** [comment]
The reason you are seeing the output from PROC PRINT twice is because you used the collectcode=TRUE option in the first SAS code chunk.  You would generally only use collectcode=TRUE when you are using SAS code which produces a data set stored in the WORK library (code that produces permanent SAS data sets does not need to be repeated, although the LIBNAME statement does).

In addition, changes in `knitr` and `SASmarkdown` make it possible to simplify your set up (see the attached file, sasmarkdown-revised.rmd).  While these changes are not strictly necessary – the document still produces the correct output the way you wrote it – they should make it a little easier to read and write.

**Comment by mgdondon** [comment]
Thank you for the explanation. It is however a limitation because in that case, new code chunk is considered as new SAS session. Not only the libname statement has to be repeated but also formats definitions, macros definitions…

The sasmarkdown-revised.rmd file was not attached. Can you send it or copy the new set up ?

Thank you,

**Comment by Hemken** [comment]
---
title: "Test SASmarkdown"
output:
  html_document:
    df_print: paged
    toc: yes
  word_document:
    toc: yes
  pdf_document:
    toc: yes
date: "11/03/2020"
---

# Session info
```{r}
library(SASmarkdown)
```

```{r}
sessionInfo()
```

# SAS program
```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = TRUE)
# saslog_hookset("source")

# saspath <- "C:/Program Files/SASHome/SASFoundation/9.4/sas.exe"
sasopts <- "-nosplash -ls 85"

knitr::opts_chunk$set(#engine='sas', engine.path=saspath,
                      engine.opts=list(sas=sasopts, saslog=sasopts), comment="")
```

```{sas, error=TRUE}
proc print data=sashelp.class (obs=3);
run;
```

```{sas, error=TRUE}
proc means data=sashelp.class;
  var Age Height Weight; 
run;
```

**Comment by Hemken** [comment]
[sasmarkdown-revised.rmd.txt](https://github.com/Hemken/SASmarkdown/files/4324414/sasmarkdown-revised.rmd.txt)

Yes, each code chunk is a separate SAS session.  collectcode=TRUE creates an autoexec.sas file.

One  system that gives you a continuous connection to a SAS session is a Jupyter notebook.  The downside to these is that they take quite a bit of work to set up/ install all the softwre components, and they give you fewer options for html output integrated into your main text.  But for many people, a Jupyter notebook using a SAS kernel is a very nice tool.

**Comment by mgdondon** [comment]
Thank you for your response and the new Rmd file. Please excuse me for the late reply. 

Yes I did also test Jupyter notebooks. They are OK for HTML export but not for PDF export because they are based on SAS HTML outputs and IPython.HTML does not work in Jupyter notebook PDF export.

Your package works fine with the collectcode option and would be very useful if the problem of the outputs repetition could be solved.

Thank you very much,

Related issues :
- https://github.com/jupyter/nbconvert/issues/474 IPython.HTML does not work in Jupyter notebook PDF export
- https://github.com/sassoftware/sas_kernel/issues/13 Enabling inline for SAS outputs in notebook
