### ISSUE TITLE
Possible to use a SAS executable on a different machine?

### ISSUE THREAD

**Issue by jrisi256** [Hemken/SASmarkdown#13]
Hi, I'm managing a machine which is running RStudio at my company. On a separate server we have SAS running. Is there a way to point the SASmarkdown package to this executable?

I"m envisioning something like what the saspy packages does (which allows for the running of SAS code in a Python environment): https://sassoftware.github.io/saspy/install.html

**Comment by Hemken** [comment]
Saspy is more sophisticated with respect to connecting to a SAS session.  SASmarkdown is just running SAS in batch mode from the shell.  If your Rstudio machine has a “sas” command defined that sends a command to another server (along with all the arguments), then you might be able to use SASmarkdown.  You’d have to figure out how to send an autoexec file to the server, how to send the command .sas file, and how to retrieve any output files.

Actually, just using saspy and accepting the more limited formatting options would probably be easiest to implement and support.

**Comment by jrisi256** [comment]
To be clear, are you suggesting somehow piggybacking off of saspy which is able to use the SAS executable on another machine in order to use SASmarkdown?

**Comment by Hemken** [comment]
No, I’m suggesting you skip RStudio and run Jupyter for this purpose.

**Comment by jrisi256** [comment]
Ahh. Yes in this instance we already using Jupyter + saspy to do this. Some of the users were curious though if it could also be replicated using RStudio. It appears not for the time being! Thanks for the quick replies.

**Comment by Hemken** [comment]
My answer would be:  in principle it might work, but figuring it out sounds like a major project.  We don’t use SAS here in that way, so I won’t be doing it myself.

**Comment by danielinteractive** [comment]
@Hemken @jrisi256 Hi, just coming to this package and issue since I would also be curious in how this could work.
But then with Quarto now I guess it would be potentially even easier by using a Python chunk and saspy in there? Just found https://www.harveyl888.com/post/2022-07-02-quarto_sas_02/ which is doing exactly that.

**Comment by Hemken** [comment]
Right, SASmarkdown will only use SAS on the same machine where R is running.  Saspy can handle the case where SAS is on a remote server.  And with the recent introduction of Quarto, you should be able to render a Jupyter Notebook with a SAS kernel as a Markdown document.

--
Doug Hemken
4226I Social Science Bldg.

***@***.***
262-4327

**Comment by Hemken** [comment]
Thanks for the reference to Harvey Lieberman’s post by the way.  It looks very clearly written!

--
Doug Hemken
SSCC statistical consultant
4226i Social Science Bldg.

***@***.******@***.***>
608-262-4327
