### ISSUE TITLE
Black and White graphics output using SASmarkdown but not SAS in batch mode?

### ISSUE THREAD

**Issue by srvanderplas** [Hemken/SASmarkdown#14]
I'm having trouble figuring out exactly why SASmarkdown is generating all black-and-white figures, when the same code works in batch mode to generate color figures. 

I'm working on Ubuntu 18.04, with SAS 9.4. 

Here's some code to demonstrate the issue:
````
indoc <- '
---
title: reprex
output: html_document
---

```{r load-sas-libraries, echo =T, message = F, warning = F}
library(SASmarkdown)
sas_enginesetup()
```

```{r echo=T}
writeLines(c(
"PROC SGPLOT data=sashelp.snacks;",
"SCATTER x = date y = QtySold /",
"  markerattrs=(size=8pt symbol=circlefilled)",
"  group = product; /* maps to point color by default */",
"RUN;",
"QUIT;"
), con = "reprex.sas")
```


```{r as-in-book, engine="sashtml", engine.path = "sas"}
%include "reprex.sas";
```


```{r}
system("sas reprex.sas")
```

![](SGPlot.png)
'
knitr::knit(text=indoc, output="test.md")
rmarkdown::render("test.md")
````

Which looks like this when rendered:

![image](https://user-images.githubusercontent.com/2127125/94835537-71618300-03d7-11eb-9c5b-1a62bd671ab8.png)

As you can see, the SAS code chunk produces a black-and-white graph, while the batch output renders a graph which is produced in color.

<details><summary>Actual graph files generated</summary>

![as-in-book](https://user-images.githubusercontent.com/2127125/94836056-21cf8700-03d8-11eb-8a74-7f3aa4c19ca1.png)

![SGPlot](https://user-images.githubusercontent.com/2127125/94836129-3c096500-03d8-11eb-8969-04ed8cc3fc03.png)

</details>

I don't know SAS *that* well, so I'm open to the possibility that there is just an obvious option that I'm missing here, but if that's the case, why does batch mode produce color graphs while SASmarkdown produces black-and-white graphs?

Thanks for the help.

***

Cleanup: You can remove the files generated by this reprex from your machine using `file.remove(c("SGPlot.png","as-in-book.png", "test.md", "test.html"))` in R.

**Comment by Hemken** [comment]
Susan , it may be that I included a “minimal” style declaration in the header of the SAS file used to generate output.  In that case, you just need to include a style declaration explicitly in your code block (or in a previous code block if you are using collectcode).

**Comment by srvanderplas** [comment]
Yep, that did it, thanks!

It might be worth reconsidering the "minimal" option if only so that the default behavior is the same in SAS and SASmarkdown.

For anyone else who comes across this and doesn't know exactly what a style declaration would look like (because I didn't, not being a particularly experienced SAS user), this worked for me:

````
indoc <- '
---
title: reprex
output: html_document
---

```{r load-sas-libraries, echo =T, message = F, warning = F}
library(SASmarkdown)
sas_enginesetup()
```

```{r echo=T}
writeLines(c(
"ODS HTML style=htmlblue;",
"PROC SGPLOT data=sashelp.snacks;",
"SCATTER x = date y = QtySold /",
"  markerattrs=(size=8pt symbol=circlefilled)",
"  group = product; /* maps to point color by default */",
"RUN;",
"QUIT;"
), con = "reprex.sas")
```


```{r as-in-book, engine="sashtml", engine.path = "sas"}
%include "reprex.sas";
```


```{r}
system("sas reprex.sas")
```

![](SGPlot.png)
'
knitr::knit(text=indoc, output="test.md")
rmarkdown::render("test.md")

````

**Comment by Hemken** [comment]
Thanks for providing the example code.

If others find this annoying, please let me know.  I could consider turning this into a chunk option, I suppose.

**Comment by srvanderplas** [comment]
A chunk option sounds like an excellent way to handle it!

**Comment by Hemken** [comment]
For now this remains a SAS option, not a knitr option.  See [SASmarkdown docs](https://www.ssc.wisc.edu/~hemken/SASworkshops/Markdown/ch4.html#using-the-sashtml-engine)
