### ISSUE TITLE
8.5 chapter - possible typo

### ISSUE THREAD

**Issue by klimanekt** [Hemken/SASmarkdown#23]
I guess there is a possible typo (missing "s") in the last word of the following part of the code

knitr::opts_chunk$set(engine.opts=list(sas=sasopts, saslog=sasopts, 
                                       sashtml=sasopts, sashtmllog=sasopt))

**Comment by Hemken** [comment]
Thank you.  Fixed now.

--
Doug Hemken
SSCC statistical consultant
4226i Social Science Bldg.

***@***.******@***.***>
608-262-4327


From: klimanekt ***@***.***>
Sent: Monday, November 28, 2022 6:23 AM
To: Hemken/SASmarkdown ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Hemken/SASmarkdown] 8.5 chapter - possible typo (Issue #23)


I guess there is a possible typo (missing "s") in the last word of the following part of the code

knitr::opts_chunk$set(engine.opts=list(sas=sasopts, saslog=sasopts,
sashtml=sasopts, sashtmllog=sasopt))
