### ISSUE TITLE
highlight-style not implemented in SAS code chunks

### ISSUE THREAD

**Issue by jpiaskowski** [Hemken/SASmarkdown#28]
Hello,

Thank you for this incredible package. Do you know if it's possible to implement code highlighting for SAS code? No [code highlighting style](https://quarto.org/docs/output-formats/html-code.html#highlighting) implemented in Quarto shows up in SAS code chunks.

**Comment by Hemken** [comment]
I don’t know what is involved in a language highlighting definition?  I suppose there must be documentation somewhere?
________________________________
From: Julia Piaskowski ***@***.***>
Sent: Thursday, July 11, 2024 4:51:51 PM
To: Hemken/SASmarkdown ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Hemken/SASmarkdown] highlight-style not implemented in SAS code chunks (Issue #28)


Hello,

Thank you for this incredible package. Do you know if it's possible to implement code highlighting for SAS code? No code highlighting style<https://urldefense.com/v3/__https://quarto.org/docs/output-formats/html-code.html*highlighting__;Iw!!Mak6IKo!KXc5ESbiQ0ne9m7Fy8gLlWe7en4rNOiSHgnQI2tfcHc5FcPXSjwUbN7ViurO1EwQCX8hKV6eq_RZKpML1A79sMEB$> implemented in Quarto shows up in SAS code chunks.

**Comment by jpiaskowski** [comment]
Yeah, I'm confused why it works for other languages besides sas. It doesn't sound like there is anything going on with SASmarkdown that would prevent this.

**Comment by Hemken** [comment]
https://hamel.dev/notes/quarto/highlighting.html

Might provide a starting point.
________________________________

**Comment by jpiaskowski** [comment]
This looks great, thank you so much!
