### ISSUE TITLE
Error: attempt to use zero-length variable name

### ISSUE THREAD

**Issue by pressleydavid** [Hemken/SASmarkdown#5]
I get the error whenever I attempt the examples at: https://www.ssc.wisc.edu/~hemken/SASworkshops/Markdown/SASmdpackage.html

Statements Executed and Log:
> install.packages("SASmarkdown")
Error in install.packages : Updating loaded packages
>Restarting R session...
> install.packages("SASmarkdown")
Installing package into ‘\\CLINICALVM1/Users/<username>/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/SASmarkdown_0.4.3.zip'
Content type 'application/zip' length 543587 bytes (530 KB)
downloaded 530 KB
>package ‘SASmarkdown’ successfully unpacked and MD5 sums checked
>The downloaded binary packages are in
	C:\Users\<username>\AppData\Local\Temp\2\RtmpsfrEvn\downloaded_packages
> help(package="SASmarkdown")
> require(SASmarkdown)
>Loading required package: SASmarkdown
sas, saslog, sashtml, and sashtmllog engines
   are now ready to use.
> saspath <- "C:/Program Files/SASHome/SASFoundation/9.4/sas.exe"
> sasopts <- "-nosplash -ls 75"
> knitr::opts_chunk$set(engine='sas', engine.path=saspath, engine.opts=sasopts, comment="")
> ```{r, engine="sas"}
>Error: attempt to use zero-length variable name

**Comment by Hemken** [comment]
I cannot replicate this error.
What operating system are you using?
Are these command issued within a source document?  Please send me the document you are trying to process?

Doug Hemken

**Comment by Hemken** [comment]
No response
