### ISSUE TITLE
SASmarkdown fails when there is a syntax error in SAS code

### ISSUE THREAD

**Issue by mgdondon** [Hemken/SASmarkdown#6]
Hello,

SASmarkdown package is OK when SAS code is OK:

``` {.r}
knitr::opts_chunk$set(echo = TRUE)
require(SASmarkdown)
```

    ## Loading required package: SASmarkdown

    ## sas, saslog, sashtml, and sashtmllog engines

    ##    are now ready to use.

``` {.r}
saspath <- "C:/Program Files/SASHome/SASFoundation/9.4/sas.exe"
sasopts <- "-nosplash -ls 75"
knitr::opts_chunk$set(engine='sas', engine.path=saspath,
                      engine.opts=sasopts, comment="")
```

``` {.sas}
proc means data=sashelp.class;
run;
```

                                  Procédure MEANS

     Variable    N        Moyenne     Ecart-type        Minimum        Maximum
     -------------------------------------------------------------------------
     Age        19     13.3157895      1.4926722     11.0000000     16.0000000
     Height     19     62.3368421      5.1270752     51.3000000     72.0000000
     Weight     19    100.0263158     22.7739335     50.5000000    150.0000000
     -------------------------------------------------------------------------

---

but fails when there is a syntax error in SAS :

``` {.sas}
proc means data sashelp.class;
run;
```

![sasmarkdown_error](https://user-images.githubusercontent.com/9783562/45492023-7c530780-b76b-11e8-9583-392706994a2d.png)

---

It would be usefull to get the SAS log as with [SASKernel](https://github.com/sassoftware/sas_kernel):

```sas
proc means data sashelp.class;
run;
```

    SAS Connection established. Subprocess id is 6648

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html>
<body>
<h2></h2>

<div class="highlight"><pre><span></span><span class="err">6</span>                                                          <span class="err">Le</span> <span class="err">Système</span> <span class="err">SAS</span>                         <span class="err">15:53</span> <span class="err">Thursday,</span> <span class="err">September</span> <span class="err">13,</span> <span class="err">2018</span><br><br><span class="s">39         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode=&#39;inline&#39;) device=svg style=HTMLBlue;</span><br><span class="s">39       ! ods graphics on / outputfmt=png;</span><br><span class="cm">NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1</span><br><span class="s">40         </span><br><span class="s">41         proc means data sashelp.class;</span><br><span class="s">                           _____________</span><br><span class="s">                           73</span><br><span class="k k-Multiline">ERROR 73-322: Un(e) = est attendu(e).</span><br><span class="s">42         run;</span><br><br><span class="cm">NOTE: The SAS System stopped processing this step because of errors.</span><br><span class="cm">NOTE: PROCEDURE MEANS used (Total process time):</span><br><span class="cm">      real time           0.01 seconds</span><br><span class="cm">      cpu time            0.01 seconds</span><br><span class="cm">      </span><br><span class="s">43         </span><br><span class="s">44         ods html5 (id=saspy_internal) close;ods listing;</span><br><span class="s">45         </span><br></pre></div>
</body>
</html>

Thanks,

**Comment by mgdondon** [comment]
Sorry, it's related to issue #3 and therefore OK.

```
```{r, engine='sas', error=TRUE}
proc means data sashelp.class;
run;
```

```
2 proc means data sashelp.class;
_____________
73
ERROR 73-322: Un(e) = est attendu(e).
3 run;
NOTE: The SAS System stopped processing this step because of errors.
NOTE: PROCEDURE MEANS used (Total process time):
real time 0.00 seconds
cpu time 0.00 seconds
ERROR: Errors printed on page 1
```

Thanks,

**Comment by Hemken** [comment]
Sorry for the slow response, and glad you found the solution.  I considered making error=TRUE a default, but I guess I decided to keep this consistent with the rest of knitr.

However, you do remind me that I need to set up an HTML5 engine!  Thanks.
