### ISSUE TITLE
Can SAShtml work with chinese version SAS?

### ISSUE THREAD

**Issue by mengxibai** [Hemken/SASmarkdown#8]
I tried to use SAS Chinese version engine sashtml to make graphics
This is mycode
![Q1](https://user-images.githubusercontent.com/48046007/57505583-7e398e80-732b-11e9-9b01-dfc8e00d95b8.PNG)
The error will be like this 
![Q2](https://user-images.githubusercontent.com/48046007/57505600-93aeb880-732b-11e9-8a0d-e5615ce2f1cd.PNG).
Or
Can SASmarkdown attach graphics on pdf file directly? when I use SAS Chinese version engine sas pdf, It will give me a PNG file for graphics.

**Comment by Hemken** [comment]
So you are trying to knit to PDF, not HTML?

**Comment by Hemken** [comment]
I have not been able to reproduce your error, but below are some notes on how to include graphs in a PDF – in short, use the `sas` engine, not the `sashtml` engine.

**Comment by Hemken** [comment]
[pdfplots.pdf](https://github.com/Hemken/SASmarkdown/files/3168951/pdfplots.pdf)

**Comment by fenguoerbian** [comment]
It's not about knitting to PDF. It's the localization configuration of SAS. When using localized config for SAS, e.g `nls/zh/sasv9.cfg` in this issue, the content of output and log files are also localized.  So in the log file there will be no `"NOTE: Writing HTML Body"`, but only `"NOTE: 正在写入 HTML Body"` which causes the `grep` call in `1:grep("NOTE: Writing HTML", out.log)` in [sashtml.r](https://github.com/Hemken/SASmarkdown/blob/1b1c8a5c9430cfa3bfb33fc9e755179dc280c602/R/sashtml.r#L65)
to return `integer(0)` hence the `argument of length 0` error.

One work around is changing the grep pattern to `"^NOTE: ([[:alpha:]]*) HTML Body"`. Also one should add `-encoding utf8` in the sas engine option if the chinese config of SAS is used.

PS: though a work around here. But the localized content also makes the [sasloghook.r](https://github.com/Hemken/SASmarkdown/blob/master/R/sasloghook.r#L21) fails to grep and remove processing time. And the localized content cannot be easily merged into the same pattern as that of English version.
